services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: garage-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - STORAGE_PATH=/var/www/html/storage

  db:
    image: mysql:9.3
    container_name: garagephp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: # "MP" Si on a un Password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Si le Password n'existe pas (dans notre cas en local)
      MYSQL_RANDOM_ROOT_PASSWORD: "yes" # Pour obtenir un Password aléatoire
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/garagephp.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
